Vaishnavi Sawant

23102A0063

CMPN - A

Week 2 & 3

In [ ]:
# Calculations with Data Vectors

# Addition
c(2,3,5,7) + c(-2,-3,-5,8)
c(2,3,5,7) + c(8,9)
c(2,3,5,7) + c(8,9,10)

# Subtraction
c(2,3,5,7) - c(-2,-3,-5,8)
c(12,13,15,17) - c(8,9)
c(12,13,15,17) - c(8,9,10)

# Multiplication
c(2,3,5,7) * c(-2,-3,-5,8)
c(2,3,5,7) * c(8,9)
c(2,3,5,7) * c(8,9,10)

# Division
c(24,20,8,16) / c(3,4,2,8)
c(24,20,8,16) / c(4,2)
c(24,20,8,16) / c(4,2,8)

[1]  0  0  0 15

[1] 10 12 13 16

Warning message in c(2, 3, 5, 7) + c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 10 12 15 15

[1]  4  6 10 -1

[1] 4 4 7 8

Warning message in c(12, 13, 15, 17) - c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 4 4 5 9

[1]  -4  -9 -25  56

[1] 16 27 40 63

Warning message in c(2, 3, 5, 7) * c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 16 27 50 56

[1] 8 5 4 2

[1]  6 10  2  8

Warning message in c(24, 20, 8, 16)/c(4, 2, 8):
“longer object length is not a multiple of shorter object length”

[1]  6 10  1  4

In [ ]:
# Assignment of Numbers and Characters

x <- 20
x

x = 20
x

y = x * 2
y

z = x + y
z

x = "apple"
x

x <- "apple1"
x

x = 'apple'
x

x <- 'apple'
x

[1] 20

[1] 20

[1] 40

[1] 60

[1] "apple"

[1] "apple1"

[1] "apple"

[1] "apple"

In [ ]:
# Knowing Numbers and Characters

x = 20

is.numeric(x)
is.character(x)

y = "apple"

is.character(y)
is.numeric(y)

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

In [ ]:
# Converting Numbers and Characters

# Number to Character

x = 20

is.numeric(x)

y = as.character(x)

is.numeric(y)

is.character(y)

y

# Character to Number

y = "apple"

is.numeric(y)

is.character(y)

z = as.numeric(y)

is.numeric(z)

is.character(z)

z

[1] TRUE

[1] FALSE

[1] TRUE

[1] "20"

[1] FALSE

[1] TRUE

Warning message:
“NAs introduced by coercion”

[1] TRUE

[1] FALSE

[1] NA

In [ ]:
# Comment Operator
# mu is the mean

# x <- 20 is treated as comment only

x = 20
x

[1] 20

In [ ]:
# Case Sensitivity

X <- 20

x <- 30

X

x

[1] 20

[1] 30

In [ ]:
# Combining Values in a Data Vector

x = c(1,2,3,4,5)

x

[1] 1 2 3 4 5

In [ ]:
# Mode

x = 6

x

mode(x)

y = "apple"

y

mode(y)

# Storage Mode

x = 6
storage.mode(x)

x = TRUE
storage.mode(x)

x = "apple"
storage.mode(x)

[1] 6

[1] "numeric"

[1] "apple"

[1] "character"

[1] "double"

[1] "logical"

[1] "character"

In [ ]:
# Infinity

3/0

5 + Inf

x = 5 + Inf

is.finite(x)

is.infinite(x)

[1] Inf

[1] Inf

[1] FALSE

[1] TRUE

In [ ]:
# R as a Calculator

# Addition
2 + 3

# Multiplication
2 * 3

# Subtraction
2 - 3

# Division
3 / 2

# Mixed Expression
2 * 3 - 4 + 5 / 6

# BODMAS
(2+3)*5 + 5 -10

(((2+3)*5 +5)-10)/2

# Blank Spaces
2+5
2 + 5
2 +5
2+ 5

[1] 5

[1] 6

[1] -1

[1] 1.5

[1] 2.833333

[1] 20

[1] 10

[1] 7

[1] 7

[1] 7

[1] 7

In [ ]:
# Addition with Scalar

c(2,3,5,7) + 10

[1] 12 13 15 17

In [ ]:
# Subtraction with Scalar

c(12,13,15,17) - 10

[1] 2 3 5 7

In [ ]:
# Multiplication with Scalar

c(2,3,5,7) * 10

[1] 20 30 50 70

In [ ]:
# Division with Scalar

c(12,13,15,17) / 10

[1] 1.2 1.3 1.5 1.7

WEEK 3

In [1]:
c(2,3,5,7) + c(-2,-3, -5, 8)

[1]  0  0  0 15

In [2]:
2^3
2**3

[1] 8

[1] 8

In [3]:
2^0.5
2**0.5
2^-0.5

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [4]:
c(2,3,5,7)^2

[1]  4  9 25 49

Power operation with vector

In [6]:
c(2,3,5,7)^c(2,3)
c(1,2,3,4,5,6)^c(2,3,4)

[1]   4  27  25 343

[1]    1    8   81   16  125 1296

Power operation with unequal vector lengths

In [7]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

Integer division with scalar

In [8]:
2 %/% 2
5 %/% 2
7 %/% 3

[1] 1

[1] 2

[1] 2

Integer division with data vector

In [9]:
c(2,3,5,7) %/% 2
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 3

[1] 1 1 2 2

Integer division with unequal vector lengths

In [10]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

Modulo division with scalars

In [11]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

Modulo division with data vector

In [12]:
c(2,3,5,7) %% 2
c(2,3,5,7) %% c(2,3)

[1] 0 1 1 1

[1] 0 0 1 1

Modulo division with unequal vector lengths

In [13]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

Maximum

In [14]:
max(1.2, 3.4, -7.8)
max( c(1.2, 3.4, -7.8) )

[1] 3.4

[1] 3.4

Minimum

In [15]:
min(1.2, 3.4, -7.8)
min( c(1.2, 3.4, -7.8) )

[1] -7.8

[1] -7.8

Arithmetic mean

In [16]:
mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 2

[1] 3

Absolute value

In [17]:
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4

[1] 1 2 3 4 5

Square root

In [18]:
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2

[1] 2 3 4 5

Sum

In [19]:
sum(c(2,3,5,7))

[1] 17

Product

In [20]:
prod(c(2,3,5,7))

[1] 210

Round

In [21]:
round(1.23)
round(1.83)

[1] 1

[1] 2

Natural logarithm

In [22]:
log(10)
log(exp(1))
log(c(10, 100, 1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

Log base 10

In [23]:
log10(10)
log10(100)
log10(c(10, 100, 1000))

[1] 1

[1] 2

[1] 1 2 3

Assignment and calculation

In [24]:
x1 = c(1,2,3,4)
x1
x2 = x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

Calculations with vector, sum and product

In [25]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

Absolute value with calculations

In [26]:
abs( c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16

4 × 2 matrix

In [27]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8) )
x
x[3,2]
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 7

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [28]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8), byrow = FALSE)
x
y = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8), byrow = TRUE)
y

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [29]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8) )
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [30]:
dim(x)
nrow(x)
ncol(x)
mode(x)
attributes(x)

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

In [31]:
help("matrix")

In [32]:
is.matrix(as.matrix(1:10))

[1] TRUE

In [34]:
data(warpbreaks)
!is.matrix(warpbreaks)
warpbreaks[1:10,]
as.matrix(warpbreaks[1:10,])

[1] TRUE

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M